version: 1
disable_existing_loggers: False

formatters:
  simple:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  detailed:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(filename)s:%(lineno)d - %(message)s'

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
  file_handler:
    class: logging.FileHandler
    level: DEBUG
    formatter: detailed
    filename: app.log
    mode: 'a'
    encoding: 'utf8'

loggers:
  mlflow_export_import:
    level: DEBUG
    handlers: [console, file_handler]
    propagate: no

root:
  level: INFO
  handlers: [console]
